# Generated by Django 4.2.7 on 2023-11-15 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foodwebsiteapp", "0003_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="categories/%Y/%m/%d")),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField()),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("image", models.ImageField(upload_to="dishes/%Y/%m/%d")),
                ("ingredients", models.TextField()),
                ("details", models.TextField(blank=True)),
                ("price", models.FloatField()),
                ("discounted_price", models.FloatField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodwebsiteapp.category",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Dish Table",},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("invoice_id", models.CharField(blank=True, max_length=100)),
                ("payer_id", models.CharField(blank=True, max_length=100)),
                ("ordered_on", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodwebsiteapp.profile",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodwebsiteapp.dish",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Order Table",},
        ),
    ]
